version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: servicedesk
      MYSQL_USER: servicedesk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: '0.25'
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: '0.1'
  meilisearch:
    image: getmeili/meilisearch:v1.7
    restart: unless-stopped
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY:-meili_master_key}
      MEILI_NO_ANALYTICS: 'true'
      MEILI_HEALTHCHECK_URL: ${MEILISEARCH_HEALTHCHECK_URL:-http://127.0.0.1:7700/health}
    volumes:
      - meilisearch-data:/meili_data
    ports:
      - '7700:7700'
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider "$${MEILI_HEALTHCHECK_URL:-http://127.0.0.1:7700/health}"']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: '0.1'
  app:
    build:
      context: .
      target: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'php', 'artisan', 'about']
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: '0.5'
  queue:
    build:
      context: .
      target: app
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    env_file:
      - .env.docker
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ['CMD', 'php', 'artisan', 'queue:restart']
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: '0.25'
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          cpus: '0.1'

volumes:
  db-data:
  meilisearch-data:
