<?php

return [
    'knowledge_base' => [
        'allowed_elements' => [
            'a',
            'abbr',
            'b',
            'blockquote',
            'br',
            'code',
            'div',
            'em',
            'figcaption',
            'figure',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'hr',
            'i',
            'img',
            'kbd',
            'li',
            'mark',
            'ol',
            'p',
            'pre',
            's',
            'small',
            'span',
            'strong',
            'sub',
            'sup',
            'table',
            'tbody',
            'td',
            'tfoot',
            'th',
            'thead',
            'tr',
            'u',
            'ul',
        ],
        'allowed_attributes' => [
            '*' => ['aria-label', 'class', 'lang', 'role', 'title'],
            'a' => ['href', 'rel'],
            'blockquote' => ['cite'],
            'code' => ['class'],
            'img' => ['alt', 'height', 'loading', 'src', 'title', 'width'],
            'pre' => ['data-language'],
            'table' => ['summary'],
            'th' => ['colspan', 'rowspan', 'scope'],
            'td' => ['colspan', 'rowspan'],
        ],
        'allowed_schemes' => ['http', 'https', 'mailto'],
        'allow_relative_links' => true,
        'allow_relative_media' => true,
        'blocked_elements' => ['script', 'style', 'iframe', 'object', 'embed', 'form'],
        'max_input_length' => 20000,
    ],
];
